openapi: 3.0.3
info:
  title: Train Service API
  version: 1.0.0
  description: REST API for searching and booking train tickets.
servers:
  - url: http://localhost:3007/api/trains
paths:
  /search:
    get:
      summary: Search for available trains
      parameters:
        - name: origin
          in: query
          required: true
          schema:
            type: string
        - name: destination
          in: query
          required: true
          schema:
            type: string
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of available trains
  /book:
    post:
      summary: Book a train ticket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                trainId:
                  type: integer
                passengers:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      age:
                        type: integer
      responses:
        '201':
          description: Train ticket booked successfully
        '400':
          description: Invalid input
